### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "2931109707",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "2931109707",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "0810cc4e9a6e46d6b51f24739d1d27d2",
  "accountNumber": "2931109707",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/0fc2a298cf2c4fd1a09778ad081da71d
